/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomCodeRouteImport } from './routes/room.$code'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as HostQuizIdRouteImport } from './routes/host.$quizId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => JoinRoute,
} as any)
const HostQuizIdRoute = HostQuizIdRouteImport.update({
  id: '/host/$quizId',
  path: '/host/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/host/$quizId': typeof HostQuizIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/host/$quizId': typeof HostQuizIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRouteWithChildren
  '/login': typeof LoginRoute
  '/host/$quizId': typeof HostQuizIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/join'
    | '/login'
    | '/host/$quizId'
    | '/join/$code'
    | '/quiz/$quizId'
    | '/room/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/join'
    | '/login'
    | '/host/$quizId'
    | '/join/$code'
    | '/quiz/$quizId'
    | '/room/$code'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/join'
    | '/login'
    | '/host/$quizId'
    | '/join/$code'
    | '/quiz/$quizId'
    | '/room/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRouteWithChildren
  LoginRoute: typeof LoginRoute
  HostQuizIdRoute: typeof HostQuizIdRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
  RoomCodeRoute: typeof RoomCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof JoinRoute
    }
    '/host/$quizId': {
      id: '/host/$quizId'
      path: '/host/$quizId'
      fullPath: '/host/$quizId'
      preLoaderRoute: typeof HostQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JoinRouteChildren {
  JoinCodeRoute: typeof JoinCodeRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinCodeRoute: JoinCodeRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRouteWithChildren,
  LoginRoute: LoginRoute,
  HostQuizIdRoute: HostQuizIdRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
  RoomCodeRoute: RoomCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
